### ISSUE TITLE
Apresentações webnar 001 a 003 de 2023

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/handbook#42]
[Trello](https://trello.com/c/kDrlPHIY/1111-propostas-webn%C3%A1rio)

**Comment by Andrelamor** [comment]
# Primeiro encontro de 2023 (07/02) - escopo:

Repassamos parte de um fluxo simulado de clonar, modificar e publicar um conjunto de dados em repositório no transparencia-mg usando as ferramentas de controle de versão do git (repo internet e máquina local), de interface gráfica (Sublime merge), de edição de texto (Sublime text),  

## Itens revistos:

- clonar repositório com CLI/prompt de comando (bash cell)

- visualizar pasta local e navegar por elas na CLI

- clonar repositório com Sublime Merge

- como configurar atalho para abrir o Sublime no CLI

- checar conteúdo do repositório no Sublime Text 

- criar e passar para nova branch via CLI

- visualizar histórico de commits, suas alterações específicas dentro dos arquivos tabulares, e se localizar nas branches no Sublime Merge

- fazer reversão de commit usando Sublime Merge

- abrir issue, PR e vincular os dois no repositório 

- fazer alteração de histórico usando reset hard

- desfazer alterações usando reversões no Sublime Merge

- conferir variáveis de ambiente (ckan-host e ckan-key) cadastradas ma máquina local

- simular atualização de conjunto de dados no homologa a partir da máquina local

- entender objetivo dos comandos do actions do repositório e como localizá-los

- compreender e localizar auxílio para possíveis mensagens de erro na CLI

## Artefatos produzidos durante o encontro:

- [Nova branch](https://github.com/transparencia-mg/acordo-judicial-reparacao-vale-projetos/tree/simula)
- [Issue](https://github.com/transparencia-mg/acordo-judicial-reparacao-vale-projetos/issues/9)
- [Histórico de alterações na nova branch](https://github.com/transparencia-mg/acordo-judicial-reparacao-vale-projetos/commits/simula)
- [Conjunto alterado em homologa - histórico alterações](https://homologa.cge.mg.gov.br/dataset/activity/acordo-judicial-reparacacao-vale-projetos)

**Comment by Andrelamor** [comment]
# 2º encontro de 2023 (14/02) - escopo:

Repassamos parte de um fluxo simulado de usar um dataset template para publicar um conjunto em ambiente de homologação

## Itens revistos:

- copiar [dataset-template](https://github.com/transparencia-mg/dataset-template)

- visualizar pasta local e navegar por elas na bash/CLI

- acessar o editor de texto Sublime na CLI

- criar e ativar ambiente virtual

- entender objetivo dos comandos do actions do repositório e como localizá-los

- instalar bibliotecas necessárias para converter e validar arquivos do repositório (frictionless, pandas, etc) 

- converter arquivo excel para csv via comando _make data_

- documentar arquivo csv criado via comando _frictionless describe(...)_

- conferir variáveis de ambiente (ckan-host e ckan-key) cadastradas ma máquina local

- simular atualização de conjunto de dados no homologa a partir da máquina local

## Fontes de consulta

https://github.com/transparencia-mg/handbook/blob/main/old_content/instalacao_python_linux.md

https://github.com/transparencia-mg/handbook/blob/main/old_content/.github/ISSUE_TEMPLATE/setup-maquina-windows.md

## Artefatos produzidos durante o encontro:

- [Novo repositório]()
- [Conjunto publicado em homologa]()

**Comment by gabrielbdornas** [comment]
@Andrelamor, pensei [nesta estrutura dentro do handbook](https://transparencia-mg.github.io/handbook/0.1/webnars/20230214_webnar_0002/) para documentarmos nossos encontros. Queria sua opinião. Achei incluir a documentação no issue difícil para acharmos os artefatos no futuro.

Concorda? Bora fazer o mesmo para o da semana passada?

**Comment by Andrelamor** [comment]
3º encontro de 2023 (28/02) - escopo:

Documentar conjunto do age-7; rever publicação em site estático

* Itens revistos:

conferência das variáveis de ambiente $HOMOLOGA_HOST e $HOMOLOGA_KEY,

atualizar o requirements.txt, incluindo as dependências necessárias

terminar a publicação do conjunto de teste no [homologa.mg.gov.br](http://homologa.mg.gov.br/)
