### ISSUE TITLE
Criar ata reunião treinamento novo dataset template conset

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/handbook#73]

**Comment by gabrielbdornas** [comment]
@AntonioMarcel, só p te lembrar deste issue. Você teve alguma dificuldade de incluir os tópicos sugeridos? Se precisar de ajuda é só falar.

**Comment by AntonioMarcel** [comment]
Aparentemente o repositório [get-youtube-transcriptions](https://github.com/gabrielbdornas/get-youtube-transcriptions)  não está funcionando.

Vou utilizar o arquivo READ.MD da raiz do repositório do [new-dataset-template](https://github.com/transparencia-mg/new-dataset-template#conjunto-de-dados---dataset) para alimentar a ata.

**Comment by AntonioMarcel** [comment]
Conforme as orientações, criei o fork do projeto, criei uma nova branch, fiz as alterações e commitei. 

Fiz então um push dessa nova branch para o github. Abri inicialmente um Pull Request para a main do meu Fork e depois abri um novo Pull Request para o repositório upstream.

Fix #939a67e5ff7df2bad4fca42f6e6e8e14f47ca72f
